[phases.setup]
nixPkgs = ["rustc", "cargo", "pkg-config", "openssl", "gcc"]

[phases.install]
cmds = [
  "cargo build --release --package dxid-node"
]

[start]
cmd = "./target/release/dxid-node --no-discovery"

[variables]
RUST_BACKTRACE = "1"
BUILD_TIMESTAMP = "2025-08-22-13-50"
