services:
  - type: web
    name: dxid-layer0
    env: rust
    plan: starter
    buildCommand: cargo build --release --bin dxid-node
    startCommand: ./target/release/dxid-node
    healthCheckPath: /health
    envVars:
      - key: RUST_VERSION
        value: 1.78.0
      - key: PORT
        value: 8080
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*.rs"
        - "**/*.toml"
        - "**/*.lock"
        - "Cargo.toml"
        - "Cargo.lock"
